apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-service
  template:
    metadata:
      labels:
        app: application-service
    spec:
      containers:
      - name: application-service
        image: gcr.io/PROJECT_ID/order-service:latest
        ports:
        - containerPort: 3000
