apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
      - name: pat-service
        image: gcr.io/PROJECT_ID/application-service:latest
        ports:
        - containerPort: 3000
