FROM node:20-alpine

# Set working directory inside container
WORKDIR /app

# Copy the index file
COPY . .

# Expose port (change if your app uses another port)
EXPOSE 3000

# Run the app
CMD ["node", "index.js"]

